module.exports = {
	defaultSettings: {
		prefix: '!',
		color: '#f1bdff',
		welcomeMessage: 'Welcome to {server} {user}!{nl}Please head over to {channel} to get started!',
		allowUserInvites: false,
		shouldLog: false,
		shouldWelcome: false,
		profanityFilter: false,
		pinboardEnabled: false,
		ownerRole: 'Not Set, Please mention Role or set Role ID',
		adminRole: 'Not Set, Please mention Role or set Role ID',
		modRole: 'Not Set, Please mention Role or set Role ID',
		welcomeChannel: 'Not Set, Please mention Channel or set Channel ID',
		rulesChannel: 'Not Set, Please mention Channel or set Channel ID',
		auditLogChannel: 'Not Set, Please mention Channel or set Channel ID',
		roleAssignChannel: 'Not Set, Please mention Channel or set Channel ID',
		streamNotifChannel: 'Not Set, Please mention Channel or set Channel ID',
		pinboardChannel: 'Not Set, Please mention Channel or set Channel ID',
	},
};